version: 2
updates: 
  # 包管理器
  - package-ecosystem: "npm"
    # package.json所在的目录
    directory: "/"
    # 每隔多少时间检测
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Shanghai"
    # commit信息
    commit-message:
      prefix: ":arrow_up: "
    ignore:
      - dependency-name: "lint-staged"
