// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        AButton: typeof import('ant-design-vue/es')['Button']
        ACard: typeof import('ant-design-vue/es')['Card']
        AImage: typeof import('ant-design-vue/es')['Image']
        AList: typeof import('ant-design-vue/es')['List']
        AListItem: typeof import('ant-design-vue/es')['ListItem']
        APopover: typeof import('ant-design-vue/es')['Popover']
        ASlider: typeof import('ant-design-vue/es')['Slider']
        ASpace: typeof import('ant-design-vue/es')['Space']
        AUpload: typeof import('ant-design-vue/es')['Upload']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
    }
}
