name: CI

on:
  push:
    branches:
      - main
      - react
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"
          cache: 'pnpm'

      - name: Cache
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{runner.OS}}-${{hashFiles('pnpm-lock.yaml')}}

      - name: Installing Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Tsc
        run: pnpm run tsc

      - name: Running Lint
        run: pnpm run lint

      - name: Running Unit Test
        run: pnpm run test:unit

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: packages/utils/coverage/clover.xml,packages/hooks/coverage/clover.xml

  E2E-Test:
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge]
    uses: ./.github/workflows/e2e.yml
    with:
      browser: ${{ matrix.browser }}
    secrets: inherit