name: E2E Test

on:
  workflow_call:
    inputs:
      browser:
        description: 'Browser used for testing'
        default: 'chrome'
        required: false
        type: string

jobs:
  test-react-components:
    uses: ./.github/workflows/e2e-react.yml
    with:
      browser: ${{ inputs.browser }}
    secrets: inherit
      